### PR TITLE
Brendan/retry accept

### PR DESCRIPTION
**Pull request by Bren2010**
- Commit 1 essentially duplicates the same logic from net/http. If Accept fails for any reason, then the current code tries to shutdown the server, but really just hangs everything up because...
- Commit 2 stops bothering to destroy background workers. BackgroundPool.Destroy blocks forever, waiting for BackgroundPool.worker to exit (which it never will because nothing is consuming randoms). This stops the server from ever completing shutdown.

### CODE REVIEW

**Comment by joshlf** [comment]
Would it be possible to fix the hanging issue by closing the channel? Ie, add a `Close` method to `ecdsa.SyncRandBuffer`? I'd prefer to actually fix this if we can rather than just leak resources.

**Comment by Bren2010** [comment]
I used a context, because it feels more appropriate (and also because it's funny to me).

**Comment by joshlf** [comment]
Awesome, and you've verified that this doesn't hang like the old code did?

**Comment by Bren2010** [comment]
Yes, I have

**Pull request merged**
