### PR TITLE
remove gokeyless-tester and OpActivate

### PR DESCRIPTION
**Pull request by lziest**
we don't need a web service to test keyserver

### CODE REVIEW

**Comment by lziest** [comment]
@kisom @elithrar @Bren2010 @jkroll-cf please review

**Comment by kisom** [comment]
From a codebase perspective, the diff LGTM. As for removing activations and the keyless tester, I'll defer to @elithrar on that.

**Comment by lziest** [comment]
The activation through certificate api is untouched. I am specifically wanting to delete OpActivate because that server would return a positive response if it is waiting for a certificate and it will return errors when it finishes activation. Also, when a server starts without certificate, OpActivate won't work because it is impossible to establish a TLS connection to a server yet.

OpActivate works like a ping, and so has no clear reason why it exists.

**Comment by Bren2010** [comment]
LGTM

**Comment by lziest** [comment]
@elithrar unless you protest, I will merge it at the end of the day.

**Comment by elithrar** [comment]
@lziest No issues here.

**Pull request merged**
